// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pNP2XqlgYsoYY8o1y1TSAfIDM-r_8X8',
    appId: '1:181764546344:web:ec4013f9e41e347be3fa1d',
    messagingSenderId: '181764546344',
    projectId: 'tapeshare-559c7',
    authDomain: 'tapeshare-559c7.firebaseapp.com',
    storageBucket: 'tapeshare-559c7.firebasestorage.app',
    measurementId: 'G-1Z989LFF6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-EPLYjAg_P7ER3WMIqO4RKwke9i4hEE',
    appId: '1:181764546344:android:423a3de6fa09e7c3e3fa1d',
    messagingSenderId: '181764546344',
    projectId: 'tapeshare-559c7',
    storageBucket: 'tapeshare-559c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRmBRyu2A2dW5a4h6xYUhaJX52ByxI8Q',
    appId: '1:181764546344:ios:689cbac5058ec238e3fa1d',
    messagingSenderId: '181764546344',
    projectId: 'tapeshare-559c7',
    storageBucket: 'tapeshare-559c7.firebasestorage.app',
    iosBundleId: 'com.example.tapeshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRmBRyu2A2dW5a4h6xYUhaJX52ByxI8Q',
    appId: '1:181764546344:ios:689cbac5058ec238e3fa1d',
    messagingSenderId: '181764546344',
    projectId: 'tapeshare-559c7',
    storageBucket: 'tapeshare-559c7.firebasestorage.app',
    iosBundleId: 'com.example.tapeshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pNP2XqlgYsoYY8o1y1TSAfIDM-r_8X8',
    appId: '1:181764546344:web:1690b12bb3803bd5e3fa1d',
    messagingSenderId: '181764546344',
    projectId: 'tapeshare-559c7',
    authDomain: 'tapeshare-559c7.firebaseapp.com',
    storageBucket: 'tapeshare-559c7.firebasestorage.app',
    measurementId: 'G-TEPXXB9KMM',
  );
}
